CREATE DATABASE GestionActivos;
USE GestionActivos;

CREATE TABLE ACTIVOS(
ID INT PRIMARY KEY auto_increment,
NOMBRE NVARCHAR(50),
DESCRIPCION NVARCHAR(100),
FCOMPRA NVARCHAR(10),
FINSTALACION NVARCHAR(10),
TVIDA NVARCHAR(20),
GARANTIA NVARCHAR(20)
);

SELECT * FROM ACTIVOS;

CREATE TABLE TECNICOS(
ID INT PRIMARY KEY auto_increment,
NOMBRE NVARCHAR(100),
APELLIDO NVARCHAR(100),
DNI INT,
TELEFONO INT
);

SELECT * FROM TECNICOS;

CREATE TABLE CRONOGRAMAS(
ID INT PRIMARY KEY auto_increment,
IDMAQUINA INT,
IDTECNICO INT,
TMANTENIMIENTO NVARCHAR(50),
FINICIO NVARCHAR(10),
FFIN NVARCHAR(10),
OBSERVACION NVARCHAR(200),
FALLAS NVARCHAR(200),
FOREIGN KEY (IDMAQUINA) REFERENCES ACTIVOS(ID),
FOREIGN KEY (IDTECNICO) REFERENCES TECNICOS(ID)
);

SELECT * FROM CRONOGRAMAS;
